// Shiro FloatPopover motion and appearance, with static app adapters.
import { autoUpdate, flip, offset, shift, useFloating, type Placement } from '@floating-ui/react-dom';
import { AnimatePresence, motion, useReducedMotion } from 'motion/react';
import { cloneElement, useEffect, useRef, useState, type ReactElement, type ReactNode } from 'react';
import { createPortal, flushSync } from 'react-dom';
import { Drawer } from 'vaul';
import { clsxm } from './upstream/adapters';
import { microReboundPreset } from './upstream/spring';
export function FloatPopover({children,triggerElement,trigger='hover',placement='bottom-start',type='popover',asChild=false,mobileAsSheet=false,headless=false,wrapperClassName,popoverClassNames,popoverWrapperClassNames,strategy="absolute",offset:offsetValue=10}: {children:ReactNode;triggerElement:ReactElement<any>;trigger?:'hover'|'click'|'both';placement?:Placement;type?:'tooltip'|'popover';asChild?:boolean;mobileAsSheet?:boolean;headless?:boolean;wrapperClassName?:string;popoverClassNames?:string;popoverWrapperClassNames?:string;strategy?:"fixed"|"absolute";offset?:number}) {
  const reduced = useReducedMotion();
  const [open,setOpen]=useState(false),[mobile,setMobile]=useState(false);
  const [portalKey,setPortalKey]=useState(0);
  useEffect(()=>{const reset=()=>flushSync(()=>{clearTimeout(timer.current);setOpen(false);setPortalKey(key=>key+1);});document.addEventListener('astro:before-swap',reset);return()=>document.removeEventListener('astro:before-swap',reset);},[]);
  const timer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined);
  const {refs,floatingStyles,isPositioned}=useFloating({placement,strategy,transform:false,middleware:[flip({padding:20}),offset(offsetValue),shift({padding:16,crossAxis:true})],whileElementsMounted:autoUpdate});
  useEffect(()=>{const mq=matchMedia('(max-width:1024px)');const update=()=>setMobile(mq.matches);update();mq.addEventListener('change',update);return()=>{mq.removeEventListener('change',update);clearTimeout(timer.current);};},[]);
  useEffect(()=>{if(!open||(mobile&&mobileAsSheet))return;const close=(e:Event)=>{if(!(refs.reference.current instanceof Element && refs.reference.current.contains(e.target as Node))&&!refs.floating.current?.contains(e.target as Node))setOpen(false);};const key=(e:KeyboardEvent)=>{if(e.key==='Escape')setOpen(false);};document.addEventListener('pointerdown',close);document.addEventListener('keydown',key);return()=>{document.removeEventListener('pointerdown',close);document.removeEventListener('keydown',key);};},[open,refs,mobile,mobileAsSheet]);
  if(mobile&&mobileAsSheet)return <Drawer.Root key={portalKey} open={open} onOpenChange={setOpen}><Drawer.Trigger asChild>{triggerElement}</Drawer.Trigger><Drawer.Portal><Drawer.Overlay className="fixed inset-0 z-[999] bg-neutral-800/40"/><Drawer.Content aria-describedby={undefined} className="fixed inset-x-0 bottom-0 z-[1000] flex max-h-[calc(100svh-5rem)] flex-col rounded-t-[10px] bg-base-100 p-4"><div className="mx-auto mb-8 h-1.5 w-12 shrink-0 rounded-full bg-zinc-300 dark:bg-neutral-800"/><Drawer.Title className="sr-only">详情</Drawer.Title>{children}</Drawer.Content></Drawer.Portal></Drawer.Root>;
  const show=()=>{clearTimeout(timer.current);setOpen(true);},hide=()=>{clearTimeout(timer.current);timer.current=setTimeout(()=>{const focused=document.activeElement;if(refs.floating.current?.contains(focused)||(refs.reference.current instanceof Element&&refs.reference.current.contains(focused)))return;setOpen(false);},80);};
  const listeners={onClick:trigger==='click'||trigger==='both'?show:undefined,onMouseOver:trigger!=='click'?show:undefined,onMouseOut:trigger!=='click'?hide:undefined,onFocus:show,onBlur:hide};
  return <>{asChild?cloneElement(triggerElement,{...listeners,ref:refs.setReference}):<span className={clsxm("inline-block",wrapperClassName)} ref={refs.setReference} {...listeners}>{triggerElement}</span>}{typeof document !== 'undefined' && createPortal(<AnimatePresence key={portalKey}>{open&&<div className={clsxm("float-popover pointer-events-auto relative z-[99]",popoverWrapperClassNames)} onMouseOver={show} onMouseOut={hide} onFocus={show} onBlur={event=>{if(!event.currentTarget.contains(event.relatedTarget))hide();}}><motion.div ref={refs.setFloating} tabIndex={-1} role={type==='tooltip'?'tooltip':'dialog'} className={clsxm(`${headless?'':'rounded-xl border border-zinc-400/20 p-4 outline-hidden backdrop-blur-lg dark:border-zinc-500/30 bg-white/80 dark:bg-neutral-900/80'} shadow-perfect relative z-[2] ${type==='tooltip'?'max-w-[25rem] break-all rounded-xl px-4 py-2':''}`,popoverClassNames)} initial={reduced?false:{y:'10px',opacity:0}} animate={{y:'0px',opacity:1}} exit={{y:reduced?'0px':'10px',opacity:0,transition:{type:'tween',duration:reduced?0:.2}}} transition={reduced?{duration:0}:microReboundPreset} style={{...floatingStyles,visibility:isPositioned?'visible':'hidden'}}>{children}</motion.div></div>}</AnimatePresence>,document.body)}</>;
}
