// Original modal desktop geometry / motion and mobile PresentSheet, with a shared static stack.
import {CloseIcon} from './upstream/close';
import * as Dialog from '@radix-ui/react-dialog';
import { AnimatePresence, motion, useDragControls, useAnimationControls } from 'motion/react';
import { useEffect, useRef, useState, useSyncExternalStore, type ReactNode } from 'react';
import { Drawer } from 'vaul';
import { flushSync } from 'react-dom';
import { microReboundPreset } from './upstream/spring';
type Item={id:number;title:ReactNode;content:ReactNode;clickOutsideToDismiss?:boolean};
let stack:Item[]=[],serial=0;const subscribers=new Set<()=>void>();
const emit=()=>subscribers.forEach(listener=>listener());
export function presentModal(title:ReactNode,content:ReactNode,options:{clickOutsideToDismiss?:boolean}={}){document.dispatchEvent(new CustomEvent('shiro:modal:present',{detail:{title,content,...options}}));}
export function dismissAll(){document.dispatchEvent(new Event('shiro:modal:dismiss-all'));}
function dismiss(id:number){stack=stack.filter(item=>item.id!==id);emit();}
type Entry={title:string;url:string;created:string;tags:string[]};
export default function ModalRoot({entries}:{entries:Entry[]}) {
  const [presenceKey,setPresenceKey]=useState(0);
  useEffect(()=>{const reset=()=>flushSync(()=>{dismissAll();setPresenceKey(key=>key+1);});document.addEventListener('astro:before-swap',reset);return()=>document.removeEventListener('astro:before-swap',reset);},[]);
  const items=useSyncExternalStore(listener=>{subscribers.add(listener);return()=>subscribers.delete(listener);},()=>stack,()=>empty);
  useEffect(()=>{const present=(event:Event)=>{const {title,content,clickOutsideToDismiss}=(event as CustomEvent<Omit<Item,'id'>>).detail;stack=[...stack,{id:++serial,title,content,clickOutsideToDismiss}];emit();};const clear=()=>{stack=[];emit();};document.addEventListener('shiro:modal:present',present);document.addEventListener('shiro:modal:dismiss-all',clear);const click=(event:MouseEvent)=>{const target=(event.target as Element).closest<HTMLElement>('[data-tag]');if(!target||event.ctrlKey||event.metaKey)return;event.preventDefault();event.stopPropagation();const name=target.dataset.tag!;presentModal(`Tag: ${name}`,<ul className="shiro-timeline">{entries.filter(entry=>entry.tags.includes(name)).map(entry=><li key={entry.url} className="flex items-center justify-between"><span className="flex min-w-0 shrink items-center"><span className="mr-2 inline-block tabular-nums">{Intl.DateTimeFormat('en-us',{month:'2-digit',day:'2-digit',year:'2-digit'}).format(new Date(entry.created))}</span><a onClick={dismissAll} href={entry.url} className="min-w-0 truncate leading-6"><span className="min-w-0 truncate">{entry.title}</span></a></span></li>)}</ul>);};document.addEventListener('click',click,true);return()=>{document.removeEventListener('shiro:modal:present',present);document.removeEventListener('shiro:modal:dismiss-all',clear);document.removeEventListener('click',click,true);};},[entries]);
  return <AnimatePresence key={presenceKey}>{items.map((item,index)=><Modal key={item.id} item={item} index={index}/>)}</AnimatePresence>;
}
const empty:Item[]=[];
function Modal({item,index}:{item:Item;index:number}){const [mobile,setMobile]=useState(false);const animation=useAnimationControls();useEffect(()=>{animation.start({scale:1,opacity:1});},[animation]);const controls=useDragControls(),edge=useRef<HTMLDivElement>(null);useEffect(()=>{const mq=matchMedia('(max-width:1024px)'),update=()=>setMobile(mq.matches);update();mq.addEventListener('change',update);return()=>mq.removeEventListener('change',update);},[]);
  if(mobile)return <Drawer.Root open onOpenChange={open=>{if(!open)dismiss(item.id);}}><Drawer.Portal><Drawer.Overlay className="fixed inset-0 bg-neutral-800/40" style={{zIndex:999+index}}/><Drawer.Content aria-describedby={undefined} className="fixed inset-x-0 bottom-0 flex max-h-[calc(100svh-5rem)] flex-col rounded-t-[10px] bg-base-100 p-4" style={{zIndex:1000+index}}><div className="mx-auto mb-8 h-1.5 w-12 shrink-0 rounded-full bg-zinc-300 dark:bg-neutral-800"/><Drawer.Title className="-mt-4 mb-4 flex justify-center text-lg font-medium">{item.title}</Drawer.Title><div className="overflow-auto">{item.content}</div></Drawer.Content></Drawer.Portal></Drawer.Root>;
  return <Dialog.Root open onOpenChange={open=>{if(!open)dismiss(item.id);}}><Dialog.Portal><Dialog.Content asChild aria-describedby={undefined}><div ref={edge} className="center fixed inset-0 flex" style={{zIndex:101+index}} onClick={()=>{if(item.clickOutsideToDismiss){dismiss(item.id);return;}animation.start({scale:1.05,transition:{duration:.06}}).then(()=>animation.start({scale:1}));}}><motion.div initial={{scale:.96,opacity:0}} animate={animation} exit={{scale:.96,opacity:0}} transition={microReboundPreset} drag dragControls={controls} dragListener={false} dragElastic={0} dragMomentum={false} dragConstraints={edge} className="relative flex flex-col overflow-hidden rounded-lg bg-zinc-50/90 dark:bg-neutral-900/90 p-2 shadow-2xl shadow-stone-300 backdrop-blur-xs dark:shadow-stone-800 max-h-[70vh] min-w-[300px] max-w-[90vw] lg:max-h-[calc(100vh-20rem)] lg:max-w-[70vw] border border-slate-200 dark:border-neutral-800" onClick={event=>event.stopPropagation()}><header className="relative flex items-center" onPointerDown={event=>controls.start(event)}><Dialog.Title className="shrink-0 grow items-center px-4 py-1 text-lg font-medium">{item.title}</Dialog.Title><Dialog.Close aria-label="关闭" className="p-2"><CloseIcon/></Dialog.Close></header><hr className="my-2 h-[0.5px] shrink-0 border-0 border-slate-200 bg-black/30 opacity-80 dark:border-neutral-800 dark:bg-white/30"/><div className="min-h-0 shrink grow overflow-auto px-4 py-2">{item.content}</div></motion.div></div></Dialog.Content></Dialog.Portal></Dialog.Root>;
}
