import { useEffect, useState } from 'react';
import { FloatPanel } from './upstream/FloatPanel';
import { Select } from './upstream/Select';
import { MotionButtonBase } from './upstream/MotionButton';
import { Tag } from './upstream/Tag';
import { presentModal } from './ModalRoot';
import { RootPortal } from './upstream/adapters';
type Mode='compact'|'loose';
export default function PostSettings({tags}:{tags:{name:string;count:number}[]}){
  const [ready,setReady]=useState(false);
  const [mode,setMode]=useState<Mode>('loose'),[sort,setSort]=useState('default'),[order,setOrder]=useState('desc');
  useEffect(()=>{let stored;try{stored=localStorage.getItem('shiro-posts-view-mode');}catch{}const params=new URLSearchParams(location.search);setMode((stored||params.get('view_mode'))==='compact'?'compact':'loose');setSort(params.get('sortBy')||'default');setOrder(params.get('orderBy')||'desc');setReady(true);},[]);
  useEffect(()=>{if(!ready)return;document.querySelectorAll<HTMLElement>('[data-post-loose]').forEach(el=>el.hidden=mode==='compact');document.querySelectorAll<HTMLElement>('[data-post-compact]').forEach(el=>el.hidden=mode!=='compact');document.querySelectorAll<HTMLElement>('.post-item > div:last-child').forEach(el=>el.classList.toggle('mt-2',mode==='loose'));try{localStorage.setItem('shiro-posts-view-mode',mode);}catch{}const params=new URLSearchParams(location.search);params.set('view_mode',mode);if(sort!=='default'){params.set('sortBy',sort);params.set('orderBy',order);}else{params.delete('sortBy');params.delete('orderBy');}history.replaceState(history.state,'',`${location.pathname}?${params}`);const list=document.querySelector('[data-post-list]');if(!list)return;Array.from(list.querySelectorAll<HTMLElement>('.post-item')).sort((a,b)=>sort==='default'?Number(b.dataset.pin==='true')-Number(a.dataset.pin==='true')||Date.parse(b.dataset.published!)-Date.parse(a.dataset.published!):(Date.parse(a.dataset[sort==='modified'?'updated':'published']!)-Date.parse(b.dataset[sort==='modified'?'updated':'published']!))*(order==='asc'?1:-1)).forEach(item=>list.append(item));},[ready,mode,sort,order]);
  const button='mt-2 flex items-center justify-center size-12 text-lg md:size-10 md:text-base outline-accent hover:opacity-100 focus:opacity-100 focus:outline-hidden rounded-xl border border-zinc-400/20 backdrop-blur-lg dark:border-zinc-500/30 dark:text-zinc-200 bg-zinc-50/80 shadow-lg dark:bg-neutral-900/80';
  return <RootPortal><div className="fixed bottom-[calc(2rem+env(safe-area-inset-bottom))] left-[calc(100vw-3rem-1rem)] z-[9] flex flex-col"><FloatPanel placement="left-end" triggerElement={<MotionButtonBase aria-label="文稿显示设置" className={button}><i className="i-mingcute-settings-5-line"/></MotionButtonBase>}><main className="relative flex w-[300px] flex-col"><section><div className="ml-1 font-bold">按...排序</div><Select className="mt-2" values={[{label:'默认',value:'default'},{label:'创建时间',value:'created'},{label:'更新时间',value:'modified'}]} value={sort} onChange={setSort}/></section><section className="mb-2 mt-4"><div className="ml-1 font-bold">顺序</div><Select className={`mt-2 ${sort==='default'?'pointer-events-none opacity-50':''}`} values={[{label:'降序',value:'desc'},{label:'升序',value:'asc'}]} value={order} onChange={setOrder}/></section><section className="mb-2 mt-4"><div className="ml-1 font-bold">列表模式</div><div className="mt-4 grid w-full grid-cols-2 gap-2 px-2">{(['compact','loose'] as const).map(value=><label key={value} className="flex items-center gap-2"><input type="radio" name="post-mode" className="radio-accent radio radio-xs" checked={mode===value} onChange={()=>setMode(value)}/>{value==='compact'?'紧凑模式':'预览模式'}</label>)}</div></section></main></FloatPanel><MotionButtonBase className={button} aria-label="标签云" onClick={()=>presentModal('标签云',<div className="flex flex-wrap gap-3">{tags.map(tag=><span key={tag.name} data-tag={tag.name}><Tag text={tag.name} count={tag.count} onClick={()=>{}}/></span>)}</div>)}><i className="i-mingcute-hashtag-line"/></MotionButtonBase></div></RootPortal>;
}
